#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x7869d85c, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x220e54f, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xe70164a5, __VMLINUX_SYMBOL_STR(iget_failed) },
	{ 0x470db77f, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x46398149, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0x9c09ffd6, __VMLINUX_SYMBOL_STR(mark_buffer_dirty_inode) },
	{ 0x8cd213cd, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xeafa546c, __VMLINUX_SYMBOL_STR(unload_nls) },
	{ 0xd2966647, __VMLINUX_SYMBOL_STR(make_bad_inode) },
	{ 0x172ada35, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0xe95c9a8b, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x5747e961, __VMLINUX_SYMBOL_STR(mem_map) },
	{ 0xa2aa7584, __VMLINUX_SYMBOL_STR(inode_permission) },
	{ 0xf3cb9361, __VMLINUX_SYMBOL_STR(generic_write_checks) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xf5b4a948, __VMLINUX_SYMBOL_STR(crc_itu_t) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0xcc81118e, __VMLINUX_SYMBOL_STR(__generic_file_write_iter) },
	{ 0xaeaf9ca, __VMLINUX_SYMBOL_STR(simple_write_end) },
	{ 0x815b5dd4, __VMLINUX_SYMBOL_STR(match_octal) },
	{ 0x34184afe, __VMLINUX_SYMBOL_STR(current_kernel_time) },
	{ 0xc913c7c4, __VMLINUX_SYMBOL_STR(block_write_begin) },
	{ 0x4ece96fb, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0xeaf71aea, __VMLINUX_SYMBOL_STR(is_bad_inode) },
	{ 0x527af331, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0x217845e4, __VMLINUX_SYMBOL_STR(generic_file_open) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0xe4d91b41, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0x4681046f, __VMLINUX_SYMBOL_STR(ll_rw_block) },
	{ 0x2ca2625b, __VMLINUX_SYMBOL_STR(__lock_buffer) },
	{ 0xf7802486, __VMLINUX_SYMBOL_STR(__aeabi_uidivmod) },
	{ 0xd3f57a2, __VMLINUX_SYMBOL_STR(_find_next_bit_le) },
	{ 0x8bc6e51b, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x2b61ad21, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x3946ac6d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x8ba9972d, __VMLINUX_SYMBOL_STR(mount_bdev) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xfa380bfa, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0xede24b01, __VMLINUX_SYMBOL_STR(__getblk_gfp) },
	{ 0xd80d57a2, __VMLINUX_SYMBOL_STR(unlock_buffer) },
	{ 0xa741497, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0xeffec1fb, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x2a3aa965, __VMLINUX_SYMBOL_STR(mpage_readpages) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xd35ec91e, __VMLINUX_SYMBOL_STR(mpage_readpage) },
	{ 0xacaefc83, __VMLINUX_SYMBOL_STR(inode_add_bytes) },
	{ 0x7ae7ca53, __VMLINUX_SYMBOL_STR(__bread_gfp) },
	{ 0xeb46fb6b, __VMLINUX_SYMBOL_STR(current_fs_time) },
	{ 0x59cd8be5, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xfbf7cf0c, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x85cfe3be, __VMLINUX_SYMBOL_STR(mpage_writepages) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x328a05f1, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x617dadf6, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xec97dd82, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xfb991ac, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0x763f9a85, __VMLINUX_SYMBOL_STR(__wait_on_buffer) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0xec9936af, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0x5bbfb5cf, __VMLINUX_SYMBOL_STR(insert_inode_locked) },
	{ 0xd10a224, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0x3e44a977, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x541ca562, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x703b20f, __VMLINUX_SYMBOL_STR(generic_file_read_iter) },
	{ 0x214aaece, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xee931785, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xd2a2fa23, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0xfe5d4bb2, __VMLINUX_SYMBOL_STR(sys_tz) },
	{ 0x15817203, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0xed99bf78, __VMLINUX_SYMBOL_STR(page_follow_link_light) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x98d72be3, __VMLINUX_SYMBOL_STR(invalidate_inode_buffers) },
	{ 0x40a9b349, __VMLINUX_SYMBOL_STR(vzalloc) },
	{ 0xa753e73c, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xbc10dd97, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0x5d4b8977, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x1a6bfc54, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0xc791274, __VMLINUX_SYMBOL_STR(inode_sub_bytes) },
	{ 0xcae48f1b, __VMLINUX_SYMBOL_STR(truncate_inode_pages_final) },
	{ 0x73406ed1, __VMLINUX_SYMBOL_STR(load_nls) },
	{ 0x371fb58, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{ 0xd7474240, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0x62dfd974, __VMLINUX_SYMBOL_STR(kill_block_super) },
	{ 0xaa65541, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0x3e77014c, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xeebaf751, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xafbd0a4d, __VMLINUX_SYMBOL_STR(d_tmpfile) },
	{ 0x14f37280, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0x7f1ef61, __VMLINUX_SYMBOL_STR(iput) },
	{ 0xabc60586, __VMLINUX_SYMBOL_STR(generic_file_fsync) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x8b85801c, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x895fe6c8, __VMLINUX_SYMBOL_STR(load_nls_default) },
	{ 0xe1f8b07e, __VMLINUX_SYMBOL_STR(d_splice_alias) },
	{ 0x666458e2, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0x87a8daf8, __VMLINUX_SYMBOL_STR(block_truncate_page) },
	{ 0x7dadf146, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0x20d4aa7d, __VMLINUX_SYMBOL_STR(generic_readlink) },
	{ 0xaca1a344, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x827ace7d, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0xc07566f6, __VMLINUX_SYMBOL_STR(__blockdev_direct_IO) },
	{ 0x63c4d61f, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0xf5ed58d5, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0xd837923e, __VMLINUX_SYMBOL_STR(ioctl_by_bdev) },
	{ 0x28a6ece5, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0xd2a1a1c9, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x5479224a, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x99bb8806, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xb6a6dc7f, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0x8d73278e, __VMLINUX_SYMBOL_STR(hex_asc_upper) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x13aea4d8, __VMLINUX_SYMBOL_STR(grab_cache_page_write_begin) },
	{ 0xdd476dfe, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0xa3db1a8b, __VMLINUX_SYMBOL_STR(page_put_link) },
	{ 0xfa7ddd8a, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0x986a0f5c, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x88ed9630, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0x8d7c4147, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0xa54f4768, __VMLINUX_SYMBOL_STR(clear_nlink) },
	{ 0xee89764f, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0x4dec6038, __VMLINUX_SYMBOL_STR(memscan) },
	{ 0x983e2233, __VMLINUX_SYMBOL_STR(vfs_fsync_range) },
	{ 0xb93a6099, __VMLINUX_SYMBOL_STR(inode_init_owner) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "82E22D03A1F1B639E95B56E");
